// Get Initial Job Details
export const GET_JOB_DETAILS = 'GET_JOB_DETAILS'
export const GET_JOB_DETAILS_SUCCESS = 'GET_JOB_DETAILS_SUCCESS'

// Authentication
export const AUTH_LOGIN_POST = 'AUTH_LOGIN_POST';
export const AUTH_LOGIN_POST_SUCCESS = 'AUTH_LOGIN_POST_SUCCESS';

export const AUTH_REGISTER_POST = 'AUTH_REGISTER_POST';
export const AUTH_REGISTER_POST_SUCCESS = 'AUTH_REGISTER_POST_SUCCESS';

export const AUTH_FORGET_PASSWORD_POST = 'AUTH_FORGET_PASSWORD_POST';
export const AUTH_FORGET_PASSWORD_POST_SUCCESS = 'AUTH_FORGET_PASSWORD_POST_SUCCESS';

export const AUTH_LOGOUT_POST = 'AUTH_LOGOUT_POST';
export const AUTH_LOGOUT_POST_SUCCESS = 'AUTH_LOGOUT_POST_SUCCESS';

// Common error dispatcher
export const COMMON_ERROR = 'COMMON_ERROR';
export const COMMON_ERROR_CLOSE = 'COMMON_ERROR_CLOSE';